# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 04:44
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountuser',
            old_name='wechatOpenID',
            new_name='personID',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='major',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='mobileOn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
    ]
