# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishTime', models.DateTimeField(verbose_name=b'publishing time')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name=b'Holding date')),
                ('position', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('type', models.IntegerField()),
                ('adminOrganization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
