# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='groupID',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
