# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(verbose_name='Holding time')),
                ('position', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('type', models.IntegerField()),
                ('groupID', models.CharField(default='', max_length=255)),
                ('student', models.ManyToManyField(related_name='student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ManyToManyField(related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
