# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
