# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_remove_activity_groupid'),
        ('signInEvent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signinevent',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity.Activity'),
        ),
    ]
